### ISSUE TITLE
Will you open source the code of this project？

### ISSUE THREAD

**Issue by xiangcool** [shibajee/realtek-uad-dts-mod#1]

**Comment by shibajee** [comment]
There is no "code", I mean not something that significant to publish. The mod stuffs, all this magic  only happen in HDXRT.inf and HDXRTSST.inf file. Rest of the files r untouched. Now about the .inf file, it's not entirely opensource, I used some existing code from realtek. Let me explain [this](https://cloud.disroot.org/s/DopGYaTC8gDA6HW) is an official file and folder layout of realtek uad driver installer. How many .inf file r there ? 8/9, I made this 8/9 inf to a single unified inf file then add some extra lines to make support various APO like dts/nahimic. Here is the [diffcheck](https://www.diffchecker.com/QnkDCzYT) for unified generic vs dts mod. @xiangcool

**Comment by xiangcool** [comment]
thanks for explanation, I almost understand your means,
I have one more question , you developed these customer APO like dts/nahimic by yourself , or download INF and DLL from somewhere ? @shibajee

**Comment by shibajee** [comment]
No, I don't make any apo files/dlls or anything. This APO files r come from official dts/nahimic/dolby team, I just grab them from various motherboard official driver site. This apo files r motherboard vendor specific. Suppose MSI motherboards only support nahimic, Asus support dts effect. So I get this files from msi and asus website. Then I modified the inf file make it available for any motherboard/laptop that has realtek audio chip. @xiangcool
